### ISSUE TITLE
DM dev branch quality control

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#269]
The following quality checks and fixes needs to be performed before merging to master:

**Integration tests are potential failing**

- [x]  templates/backend_service/tests/integration/backend_service.bats
- [ ]  templates/bastion/tests/integration/bastion.bats
- [x]  templates/bigquery/tests/integration/bigquery.bats
- [ ]  templates/cloud_sql/tests/integration/clous_sql.bats 
(Deletion fails)
- [x]  templates/dns_managed_zone/tests/integration/dns_mz_cross_project.bats 
(Likely just my permission issues, please confirm)
- [X] SKIP templates/forseti/tests/integration/forseti.bats
- [ ]  templates/haproxy/tests/integration/haproxy.bats
- [x]  templates/healthcheck/tests/integration/healthcheck.bats
- [x]  templates/instance_template/tests/integration/instance_template_networks.bats
- [x]  templates/instance/tests/integration/instance_1_nic.bats
- [x]  templates/instance/tests/integration/instance_2_nics.bats
- [x]  templates/instance/tests/integration/instance.bats
- [x]  templates/instance/tests/integration/instance_template/instance_template.bats
- [x]  templates/logsink/tests/integration/logsink.bats
- [ ]  templates/nat_gateway/tests/integration/nat_gateway.bats
- [ ]  templates/project/tests/integration/project.bats #266 
- [X]  templates/pubsub/tests/integration/pubsub.bats #265 
- [ ]  templates/route/tests/integration/route.bats
- [x]  templates/shared_vpc_subnet_iam/tests/integration/shared_vpc_subnet_iam.bats

**Schema violation issues (unexpected properties)**
- [ ]  dm/templates/backend_service/examples/backend_service_global.yaml #272
- [ ]  dm/templates/cloudbuild/examples/cloudbuild_trigger.yaml #274 
- [x]  dm/templates/external_load_balancer/examples/external_load_balancer_http.yaml
- [x]  dm/templates/external_load_balancer/examples/external_load_balancer_https.yaml
- [x]  dm/templates/gke/examples/gke_regional_private.yaml
- [x]  dm/templates/healthcheck/examples/healthcheck.yaml #270 - fixed
- [x]  dm/templates/interconnect/examples/interconnect_dedicated.yaml
- [x]  dm/templates/logsink/examples/billingaccount_logsink_bucket_destination.yaml
- [x]  dm/templates/logsink/examples/folder_logsink_bq_destination.yaml
- [x]  dm/templates/logsink/examples/org_logsink_pubsub_destination.yaml
- [x]  dm/templates/logsink/examples/project_logsink_bucket_destination.yaml
- [x]  dm/templates/runtime_config/examples/runtime_config.yaml
- [x]  dm/templates/vpn/examples/vpn.yaml

**Error compiling Python**
- [x]  dm/templates/gke/gke.py

**Comment by nick4fake** [comment]
templates/bastion/tests/integration/bastion.bats
![image](https://user-images.githubusercontent.com/1065993/63098776-4d957080-bf7c-11e9-8c63-85a3dd982628.png)

**Comment by nick4fake** [comment]
templates/backend_service/tests/integration/backend_service.bats
![image](https://user-images.githubusercontent.com/1065993/63099308-7ec27080-bf7d-11e9-8706-f4b7a4a81cf9.png)

**Comment by nick4fake** [comment]
templates/bigquery/tests/integration/bigquery.bats
It fails now for me, but I've checked it previously. Might be a race condition:
![image](https://user-images.githubusercontent.com/1065993/63100595-11640f00-bf80-11e9-9cc4-52f45a1b78bf.png)

**Comment by nick4fake** [comment]
I has worked several times, but I've [fixed dependsOn anyway](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/282/files#diff-5b70b8421b738d7b84914133992c23b7R61):
![image](https://user-images.githubusercontent.com/1065993/63103457-da90f780-bf85-11e9-9e28-d4bedeb5e494.png)

**Comment by nick4fake** [comment]
templates/cloud_sql/tests/integration/clous_sql.bats
Works for me
![image](https://user-images.githubusercontent.com/1065993/63103594-14fa9480-bf86-11e9-855c-cf633912fe79.png)

**Comment by nick4fake** [comment]
templates/dns_managed_zone/tests/integration/dns_mz_cross_project.bats
Works for me
![dns](https://user-images.githubusercontent.com/1065993/63377720-4cf44400-c399-11e9-999f-82228911860f.PNG)

**Comment by nick4fake** [comment]
templates/haproxy/tests/integration/haproxy.bats
After adding compute viewer to default compute service account it works:
![image](https://user-images.githubusercontent.com/1065993/63381522-82049480-c3a1-11e9-9e21-fb23d229129f.png)

**Comment by nick4fake** [comment]
templates/healthcheck/tests/integration/healthcheck.bats
There were collisions in test names:
![health](https://user-images.githubusercontent.com/1065993/63384312-41a81500-c3a7-11e9-8efe-d6191268fd6c.PNG)

**Comment by nick4fake** [comment]
templates/instance_template/tests/integration/instance_template_networks.bats
There was a local problem related to deployment name length. While it is not a big deal, I've fixed test to truncate it. + There was a problem with first/second nets tests
![it](https://user-images.githubusercontent.com/1065993/63386102-ef68f300-c3aa-11e9-9150-b7c6426db548.PNG)

**Comment by nick4fake** [comment]
templates/instance/tests/integration/instance_1_nic.bats
templates/instance/tests/integration/instance_2_nics.bats
Added fix to PR:
![nic1](https://user-images.githubusercontent.com/1065993/63386832-9d28d180-c3ac-11e9-9cce-ac6c11b07e05.PNG)
![nic2](https://user-images.githubusercontent.com/1065993/63387194-7f0fa100-c3ad-11e9-96d2-fa2e02e72ee2.PNG)

**Comment by nick4fake** [comment]
templates/instance/tests/integration/instance.bats
Fixed in PR:
![instance](https://user-images.githubusercontent.com/1065993/63387684-c34f7100-c3ae-11e9-98d0-df884e6e26f3.PNG)

**Comment by nick4fake** [comment]
templates/instance/tests/integration/instance_template/instance_template.bats
Fixed in PR:
![itm](https://user-images.githubusercontent.com/1065993/63387694-ccd8d900-c3ae-11e9-84ee-4ac6f923ad1c.PNG)

**Comment by nick4fake** [comment]
As I've told you a while ago, I can not test templates/logsink/tests/integration/logsink.bats due to missing permissions

**Comment by nick4fake** [comment]
templates/nat_gateway/tests/integration/nat_gateway.bats
After adding Compute instance admin and service account user to PROJECT-compute@developer.gserviceaccount.com, it works:
![nat](https://user-images.githubusercontent.com/1065993/63389722-5390b480-c3b5-11e9-99a4-ea920b69ecd7.PNG)

**Comment by nick4fake** [comment]
templates/shared_vpc_subnet_iam/tests/integration/shared_vpc_subnet_iam.bats
There was a missing file, fixed in PR. I've also added compute admin to the system service account. Works now:
![sharedvpc](https://user-images.githubusercontent.com/1065993/63390653-84beb400-c3b8-11e9-85bb-f9bd12c77b66.PNG)

**Comment by nick4fake** [comment]
Everything is fixed except:

- logsink: I need your help with additional permissions for org)
- route: I don't know yet how to make it working without breaking compatibiity
- gke: TODO
- schema violation in examples

**Comment by nick4fake** [comment]
@ocsig What is wrong with dm/templates/gke/gke.py? Tests pass correctly:
![gke](https://user-images.githubusercontent.com/1065993/63438986-ecffab00-c435-11e9-9c1f-7ad75e9b27d4.PNG)
