### ISSUE TITLE
DM templates refactoring: template and schema improvements

### ISSUE THREAD

**Issue by bohdanyurov-gl** [GoogleCloudPlatform/cloud-foundation-toolkit#47]
I've created this issue to track process of code base update.

Template/schema checklist:
- [Version "1.0.0" is added to the schema file](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/403)
- Legacy DM resources are changed to [GCP type providers](https://cloud.google.com/deployment-manager/docs/configuration/supported-gcp-types)
- [Cross-project resource creation is supported](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/337)
- [Name field is optional. DM resource name is used if it is missing](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/449)
- API versions are upgraded to the latest ones (@ocsig should be notified in the case of major upgrade)
- All properties are checked for compatibility: there are differences between legacy DM resources and type providers, some fields are missing, etc.
- All APIs calls have links to relevant API documentation page. Schema info field has list of all methods used. Add list of APIs that need to be enabled
- Schemas provide extended validation:
  - [All objects with schema have additionalProperties: false](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/413)
  - Arrays have uniqueItems: true where applicable
  - ENUMs are up to date and present where necessary
  - Default values are revised
  - ~~String values with strict checks have regex patterns~~ - too difficult to do for now
- Resource names are correctly prefixed: some templates define too common names for resources that could interfere with each other. This might be something that [we don't want though](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/401#issuecomment-471125152) but [users are struggling with](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/357)
- ~~Unit tests for schemas are added~~ - too difficult to do for now
- Integration tests pass
- Manual resource creation is done (including cross-project creation)

Template batch 1:
- [x] [autoscaler](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/67)
- [x] [cloud_function](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/52)
- [x] [cloud_router](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/51)
- [x] [cloud_spanner](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/53)
- [x] [cloud_sql](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/54)
- [x] [folder](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/55)
- [x] [gcs_bucket](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/66)
- [x] [instance](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/70)
- [x] [instance_template](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/68)
- [x] [managed_instance_group](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/69)
- [x] [network](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/56)
- [x] [network/subnetwork](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/56)
- [x] [project](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/57)

Template batch 2:
- [x] [backend_service](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/103)
- [x] [bastion](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/101)
- [x] [bigquery](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/105)
- [x] [firewall](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/99)
- [x] [gke](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/110)
- [x] [healthcheck](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/124)
- [x] [iam_custom_role](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/115)
- [x] [iam_member](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/116)
- [x] [ip_reservation](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/132)
- [x] [nat_gateway](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/123)
- [x] [kms](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/117)
- [x] [pubsub](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/118)
- [x] [route](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/119)

Template batch 3:
- [x] [dataproc](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/137)
- [x] [dns_managed_zone](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/138)
- [x] [dns_records](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/139)
- [x] [external_load_balancer](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/140)
- [x] [forwarding_rule](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/141)
- [x] [haproxy](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/142)
- [x] [internal_load_balancer](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/143)
- [x] [logsink](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/144)
- [x] [network_peering](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/145)
- [x] [org_policy](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/146)
- [x] [shared_vpc_subnet_iam](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/147)
- [x] [ssl_certificate](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/148)
- [x] [target_proxy](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/154)
- [x] [url_map](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/153)

Template batch 4:
- [x] [cloud_tasks](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/179)
- [x] [cloudbuild](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/180)
- [x] [forseti](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/181)
- [x] [interconnect](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/182)
- [x] [interconnect_attachment](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/183)
- [x] [runtime_config](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/184)
- [x] [stackdriver_metric_descriptor](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/185)
- [x] [vpn](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/186)
